services:
  nginx:
    image: nginx:latest
    container_name: nginx-reports
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html/reports:ro
